env:
  - GO111MODULE=on
before:
  hooks:
    # - go mod tidy
    # - ./scripts/completions.sh
    # You may remove this if you don't use go modules.
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - main: ./vps.go
    id: "vps"
    binary: vps
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # ignore:
    #   - goos: linux
    #     goarch: arm64
    #   - goos: windows
    #     goarch: arm64
archives:
  # - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  - replacements:
      # linux: Linux
      # darwin: Darwin
      # windows: Windows
      amd64: x86_64
      # 386: i386
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
      - '^chore:'
      - '^refactor:'
      - Merge pull request
      - Merge branch
      - go mod tidy
